apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "safe-hue-api.fullname" . }}
  labels:
    app: {{ template "safe-hue-api.name" . }}
    chart: {{ template "safe-hue-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "safe-hue-api.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "safe-hue-api.name" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.image.credentials }}
      imagePullSecrets:
        - name: {{ template "image.pullSecret.name" . }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: HUE_BRIDGE
              value: {{ .Values.hue.bridge }}
            - name: HUE_USER
              value: {{ .Values.hue.user }}
            - name: API_SECRET
              value: {{ .Values.api.secret }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
